(cl:defpackage arm_lib-srv
  (:use )
  (:export
   "MOVEARM"
   "<MOVEARM-REQUEST>"
   "MOVEARM-REQUEST"
   "<MOVEARM-RESPONSE>"
   "MOVEARM-RESPONSE"
   "MOVEGRIPPER"
   "<MOVEGRIPPER-REQUEST>"
   "MOVEGRIPPER-REQUEST"
   "<MOVEGRIPPER-RESPONSE>"
   "MOVEGRIPPER-RESPONSE"
   "FK"
   "<FK-REQUEST>"
   "FK-REQUEST"
   "<FK-RESPONSE>"
   "FK-RESPONSE"
   "IK"
   "<IK-REQUEST>"
   "IK-REQUEST"
   "<IK-RESPONSE>"
   "IK-RESPONSE"
  ))

