// Generated by gencpp from file arm_lib/fk.msg
// DO NOT EDIT!


#ifndef ARM_LIB_MESSAGE_FK_H
#define ARM_LIB_MESSAGE_FK_H

#include <ros/service_traits.h>


#include <arm_lib/fkRequest.h>
#include <arm_lib/fkResponse.h>


namespace arm_lib
{

struct fk
{

typedef fkRequest Request;
typedef fkResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct fk
} // namespace arm_lib


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arm_lib::fk > {
  static const char* value()
  {
    return "92fe4648bf1f304549e33eb855c12723";
  }

  static const char* value(const ::arm_lib::fk&) { return value(); }
};

template<>
struct DataType< ::arm_lib::fk > {
  static const char* value()
  {
    return "arm_lib/fk";
  }

  static const char* value(const ::arm_lib::fk&) { return value(); }
};


// service_traits::MD5Sum< ::arm_lib::fkRequest> should match
// service_traits::MD5Sum< ::arm_lib::fk >
template<>
struct MD5Sum< ::arm_lib::fkRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arm_lib::fk >::value();
  }
  static const char* value(const ::arm_lib::fkRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_lib::fkRequest> should match
// service_traits::DataType< ::arm_lib::fk >
template<>
struct DataType< ::arm_lib::fkRequest>
{
  static const char* value()
  {
    return DataType< ::arm_lib::fk >::value();
  }
  static const char* value(const ::arm_lib::fkRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arm_lib::fkResponse> should match
// service_traits::MD5Sum< ::arm_lib::fk >
template<>
struct MD5Sum< ::arm_lib::fkResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arm_lib::fk >::value();
  }
  static const char* value(const ::arm_lib::fkResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_lib::fkResponse> should match
// service_traits::DataType< ::arm_lib::fk >
template<>
struct DataType< ::arm_lib::fkResponse>
{
  static const char* value()
  {
    return DataType< ::arm_lib::fk >::value();
  }
  static const char* value(const ::arm_lib::fkResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARM_LIB_MESSAGE_FK_H
