// Generated by gencpp from file arm_lib/fkResponse.msg
// DO NOT EDIT!


#ifndef ARM_LIB_MESSAGE_FKRESPONSE_H
#define ARM_LIB_MESSAGE_FKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_lib
{
template <class ContainerAllocator>
struct fkResponse_
{
  typedef fkResponse_<ContainerAllocator> Type;

  fkResponse_()
    : endpos()  {
    }
  fkResponse_(const ContainerAllocator& _alloc)
    : endpos(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _endpos_type;
  _endpos_type endpos;





  typedef boost::shared_ptr< ::arm_lib::fkResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_lib::fkResponse_<ContainerAllocator> const> ConstPtr;

}; // struct fkResponse_

typedef ::arm_lib::fkResponse_<std::allocator<void> > fkResponse;

typedef boost::shared_ptr< ::arm_lib::fkResponse > fkResponsePtr;
typedef boost::shared_ptr< ::arm_lib::fkResponse const> fkResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_lib::fkResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_lib::fkResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_lib::fkResponse_<ContainerAllocator1> & lhs, const ::arm_lib::fkResponse_<ContainerAllocator2> & rhs)
{
  return lhs.endpos == rhs.endpos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_lib::fkResponse_<ContainerAllocator1> & lhs, const ::arm_lib::fkResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_lib

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_lib::fkResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_lib::fkResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_lib::fkResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_lib::fkResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_lib::fkResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_lib::fkResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_lib::fkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7be4b909778b4b252c70f3ce3b52ba00";
  }

  static const char* value(const ::arm_lib::fkResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7be4b909778b4b25ULL;
  static const uint64_t static_value2 = 0x2c70f3ce3b52ba00ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_lib::fkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_lib/fkResponse";
  }

  static const char* value(const ::arm_lib::fkResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_lib::fkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] endpos\n"
"\n"
;
  }

  static const char* value(const ::arm_lib::fkResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_lib::fkResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.endpos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct fkResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_lib::fkResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_lib::fkResponse_<ContainerAllocator>& v)
  {
    s << indent << "endpos[]" << std::endl;
    for (size_t i = 0; i < v.endpos.size(); ++i)
    {
      s << indent << "  endpos[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.endpos[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_LIB_MESSAGE_FKRESPONSE_H
