// Generated by gencpp from file arm_lib/fkRequest.msg
// DO NOT EDIT!


#ifndef ARM_LIB_MESSAGE_FKREQUEST_H
#define ARM_LIB_MESSAGE_FKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_lib
{
template <class ContainerAllocator>
struct fkRequest_
{
  typedef fkRequest_<ContainerAllocator> Type;

  fkRequest_()
    : joint_angles()
    , link_length()  {
    }
  fkRequest_(const ContainerAllocator& _alloc)
    : joint_angles(_alloc)
    , link_length(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _joint_angles_type;
  _joint_angles_type joint_angles;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _link_length_type;
  _link_length_type link_length;





  typedef boost::shared_ptr< ::arm_lib::fkRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_lib::fkRequest_<ContainerAllocator> const> ConstPtr;

}; // struct fkRequest_

typedef ::arm_lib::fkRequest_<std::allocator<void> > fkRequest;

typedef boost::shared_ptr< ::arm_lib::fkRequest > fkRequestPtr;
typedef boost::shared_ptr< ::arm_lib::fkRequest const> fkRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_lib::fkRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_lib::fkRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_lib::fkRequest_<ContainerAllocator1> & lhs, const ::arm_lib::fkRequest_<ContainerAllocator2> & rhs)
{
  return lhs.joint_angles == rhs.joint_angles &&
    lhs.link_length == rhs.link_length;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_lib::fkRequest_<ContainerAllocator1> & lhs, const ::arm_lib::fkRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_lib

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_lib::fkRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_lib::fkRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_lib::fkRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_lib::fkRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_lib::fkRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_lib::fkRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_lib::fkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9df861c61f6560d6be96e6dfae2e9d3c";
  }

  static const char* value(const ::arm_lib::fkRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9df861c61f6560d6ULL;
  static const uint64_t static_value2 = 0xbe96e6dfae2e9d3cULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_lib::fkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_lib/fkRequest";
  }

  static const char* value(const ::arm_lib::fkRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_lib::fkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] joint_angles\n"
"float32[] link_length\n"
;
  }

  static const char* value(const ::arm_lib::fkRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_lib::fkRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_angles);
      stream.next(m.link_length);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct fkRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_lib::fkRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_lib::fkRequest_<ContainerAllocator>& v)
  {
    s << indent << "joint_angles[]" << std::endl;
    for (size_t i = 0; i < v.joint_angles.size(); ++i)
    {
      s << indent << "  joint_angles[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.joint_angles[i]);
    }
    s << indent << "link_length[]" << std::endl;
    for (size_t i = 0; i < v.link_length.size(); ++i)
    {
      s << indent << "  link_length[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.link_length[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_LIB_MESSAGE_FKREQUEST_H
