// Generated by gencpp from file arm_lib/ik.msg
// DO NOT EDIT!


#ifndef ARM_LIB_MESSAGE_IK_H
#define ARM_LIB_MESSAGE_IK_H

#include <ros/service_traits.h>


#include <arm_lib/ikRequest.h>
#include <arm_lib/ikResponse.h>


namespace arm_lib
{

struct ik
{

typedef ikRequest Request;
typedef ikResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ik
} // namespace arm_lib


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arm_lib::ik > {
  static const char* value()
  {
    return "2c802ecf38b17c9f65562f8dd1868972";
  }

  static const char* value(const ::arm_lib::ik&) { return value(); }
};

template<>
struct DataType< ::arm_lib::ik > {
  static const char* value()
  {
    return "arm_lib/ik";
  }

  static const char* value(const ::arm_lib::ik&) { return value(); }
};


// service_traits::MD5Sum< ::arm_lib::ikRequest> should match
// service_traits::MD5Sum< ::arm_lib::ik >
template<>
struct MD5Sum< ::arm_lib::ikRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arm_lib::ik >::value();
  }
  static const char* value(const ::arm_lib::ikRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_lib::ikRequest> should match
// service_traits::DataType< ::arm_lib::ik >
template<>
struct DataType< ::arm_lib::ikRequest>
{
  static const char* value()
  {
    return DataType< ::arm_lib::ik >::value();
  }
  static const char* value(const ::arm_lib::ikRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arm_lib::ikResponse> should match
// service_traits::MD5Sum< ::arm_lib::ik >
template<>
struct MD5Sum< ::arm_lib::ikResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arm_lib::ik >::value();
  }
  static const char* value(const ::arm_lib::ikResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_lib::ikResponse> should match
// service_traits::DataType< ::arm_lib::ik >
template<>
struct DataType< ::arm_lib::ikResponse>
{
  static const char* value()
  {
    return DataType< ::arm_lib::ik >::value();
  }
  static const char* value(const ::arm_lib::ikResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARM_LIB_MESSAGE_IK_H
