// Generated by gencpp from file arm_lib/ikRequest.msg
// DO NOT EDIT!


#ifndef ARM_LIB_MESSAGE_IKREQUEST_H
#define ARM_LIB_MESSAGE_IKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_lib
{
template <class ContainerAllocator>
struct ikRequest_
{
  typedef ikRequest_<ContainerAllocator> Type;

  ikRequest_()
    : actuator_pose()  {
    }
  ikRequest_(const ContainerAllocator& _alloc)
    : actuator_pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _actuator_pose_type;
  _actuator_pose_type actuator_pose;





  typedef boost::shared_ptr< ::arm_lib::ikRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_lib::ikRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ikRequest_

typedef ::arm_lib::ikRequest_<std::allocator<void> > ikRequest;

typedef boost::shared_ptr< ::arm_lib::ikRequest > ikRequestPtr;
typedef boost::shared_ptr< ::arm_lib::ikRequest const> ikRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_lib::ikRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_lib::ikRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_lib::ikRequest_<ContainerAllocator1> & lhs, const ::arm_lib::ikRequest_<ContainerAllocator2> & rhs)
{
  return lhs.actuator_pose == rhs.actuator_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_lib::ikRequest_<ContainerAllocator1> & lhs, const ::arm_lib::ikRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_lib

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_lib::ikRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_lib::ikRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_lib::ikRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_lib::ikRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_lib::ikRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_lib::ikRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_lib::ikRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "731bfe7d32e7b21fcd58c1fb43ca65e7";
  }

  static const char* value(const ::arm_lib::ikRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x731bfe7d32e7b21fULL;
  static const uint64_t static_value2 = 0xcd58c1fb43ca65e7ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_lib::ikRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_lib/ikRequest";
  }

  static const char* value(const ::arm_lib::ikRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_lib::ikRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] actuator_pose\n"
;
  }

  static const char* value(const ::arm_lib::ikRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_lib::ikRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.actuator_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ikRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_lib::ikRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_lib::ikRequest_<ContainerAllocator>& v)
  {
    s << indent << "actuator_pose[]" << std::endl;
    for (size_t i = 0; i < v.actuator_pose.size(); ++i)
    {
      s << indent << "  actuator_pose[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.actuator_pose[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_LIB_MESSAGE_IKREQUEST_H
