// Generated by gencpp from file arm_lib/ikResponse.msg
// DO NOT EDIT!


#ifndef ARM_LIB_MESSAGE_IKRESPONSE_H
#define ARM_LIB_MESSAGE_IKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_lib
{
template <class ContainerAllocator>
struct ikResponse_
{
  typedef ikResponse_<ContainerAllocator> Type;

  ikResponse_()
    : new_angles()  {
    }
  ikResponse_(const ContainerAllocator& _alloc)
    : new_angles(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _new_angles_type;
  _new_angles_type new_angles;





  typedef boost::shared_ptr< ::arm_lib::ikResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_lib::ikResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ikResponse_

typedef ::arm_lib::ikResponse_<std::allocator<void> > ikResponse;

typedef boost::shared_ptr< ::arm_lib::ikResponse > ikResponsePtr;
typedef boost::shared_ptr< ::arm_lib::ikResponse const> ikResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_lib::ikResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_lib::ikResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_lib::ikResponse_<ContainerAllocator1> & lhs, const ::arm_lib::ikResponse_<ContainerAllocator2> & rhs)
{
  return lhs.new_angles == rhs.new_angles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_lib::ikResponse_<ContainerAllocator1> & lhs, const ::arm_lib::ikResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_lib

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_lib::ikResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_lib::ikResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_lib::ikResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_lib::ikResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_lib::ikResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_lib::ikResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_lib::ikResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "82fa74b77992c44ec360ba16be08cdcb";
  }

  static const char* value(const ::arm_lib::ikResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x82fa74b77992c44eULL;
  static const uint64_t static_value2 = 0xc360ba16be08cdcbULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_lib::ikResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_lib/ikResponse";
  }

  static const char* value(const ::arm_lib::ikResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_lib::ikResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] new_angles\n"
;
  }

  static const char* value(const ::arm_lib::ikResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_lib::ikResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.new_angles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ikResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_lib::ikResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_lib::ikResponse_<ContainerAllocator>& v)
  {
    s << indent << "new_angles[]" << std::endl;
    for (size_t i = 0; i < v.new_angles.size(); ++i)
    {
      s << indent << "  new_angles[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.new_angles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_LIB_MESSAGE_IKRESPONSE_H
